// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2tYXrnZ60VnkaHG5vLTBp3HcmTBl1gDk',
    appId: '1:566443021942:web:f6f7f756a4637b59d83157',
    messagingSenderId: '566443021942',
    projectId: 'voicediary-4bc37',
    authDomain: 'voicediary-4bc37.firebaseapp.com',
    storageBucket: 'voicediary-4bc37.appspot.com',
    measurementId: 'G-TKYTWT9P5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWa2J94JYXVzmYRyHGnb40Xu0k3Qrp-6E',
    appId: '1:566443021942:android:5257609dad9245d4d83157',
    messagingSenderId: '566443021942',
    projectId: 'voicediary-4bc37',
    storageBucket: 'voicediary-4bc37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-2EbwnIYKt9Vs_d3zHVRvrjxe8Gz9JyA',
    appId: '1:566443021942:ios:7e7cdf2857e33d5ad83157',
    messagingSenderId: '566443021942',
    projectId: 'voicediary-4bc37',
    storageBucket: 'voicediary-4bc37.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-2EbwnIYKt9Vs_d3zHVRvrjxe8Gz9JyA',
    appId: '1:566443021942:ios:12b7903ecf2fbeaad83157',
    messagingSenderId: '566443021942',
    projectId: 'voicediary-4bc37',
    storageBucket: 'voicediary-4bc37.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
